#!/bin/bash
set -e

run-daemon() {
    if [[ `docker ps|grep ghdld_vlsi|wc -l` = 0 ]]; then
        echo running container daemon...
        docker run --rm -it -d -v "`pwd`":"`pwd`" -w "`pwd`" -u 1000:1000 --name ghdld_vlsi ghdl/ext sleep 1h >/dev/null
        echo daemon is up
    fi
}

main() {
    run-daemon

    docker exec -w "$PWD" ghdld_vlsi python3 scripts/vunit-main.py "$@" -o out
}

main -l 2>/dev/null | awk 'BEGIN{FS="."}; /'${1-project}'/ {print $2 "." $3}'
